### ISSUE TITLE
Animating theme transition

### ISSUE THREAD

**Issue by malonehedges** [onmyway133/Themes#5]
What is the best way to add a transition when changing themes?

For example, if I have a light and dark theme, and would like it to fade between the two when the `ThemeManager.shared.currentTheme` is changed.

I am currently doing the following:
```swift
view.use(MyTheme.self) { (view, theme) in
    UIView.animate(withDuration: 1.0, animations: {
        view.backgroundColor = theme.backgroundColor
    })
 }
```
but would like to avoid having `UIView.animate` in every screen, as I'd like this behavior on all attributes.

**Comment by malonehedges** [comment]
I now only do it on the screens where you can change the theme as they are the only ones that need an animation.

**Comment by onmyway133** [comment]
@malonehedges hi sorry I didn't see this issue. I think let keep this as an exercise for users for now. But I'd say this is a nice feature to have

**Comment by malonehedges** [comment]
@onmyway133 all good! Appreciate you creating Themes.
